language: go

before_script:
  - go vet ./terraform/lambda-apigateway/...
  - env GOOS=linux ARCH=amd64 go build ./terraform/lambda-apigateway/lambda/lambda.go

deploy:
  provider: s3
  skip_cleanup: true
  region: us-east-1
  local_dir: ./terraform/lambda-apigateway/lambda/
